// Code generated by pigeon; DO NOT EDIT.

package oracle

import (
	"bytes"
	"errors"
	"fmt"
	"io"
	"math"
	"os"
	"sort"
	"strconv"
	"strings"
	"sync"
	"tsqlgrl/generic"
	"unicode"
	"unicode/utf8"
)

var g = &grammar{
	rules: []*rule{
		{
			name: "File",
			pos:  position{line: 8, col: 1, offset: 72},
			expr: &actionExpr{
				pos: position{line: 8, col: 9, offset: 80},
				run: (*parser).callonFile1,
				expr: &seqExpr{
					pos: position{line: 8, col: 9, offset: 80},
					exprs: []any{
						&zeroOrOneExpr{
							pos: position{line: 8, col: 9, offset: 80},
							expr: &ruleRefExpr{
								pos:  position{line: 8, col: 9, offset: 80},
								name: "WhiteSpace",
							},
						},
						&labeledExpr{
							pos:   position{line: 8, col: 21, offset: 92},
							label: "stmts",
							expr: &oneOrMoreExpr{
								pos: position{line: 8, col: 27, offset: 98},
								expr: &seqExpr{
									pos: position{line: 8, col: 28, offset: 99},
									exprs: []any{
										&ruleRefExpr{
											pos:  position{line: 8, col: 28, offset: 99},
											name: "Statement",
										},
										&zeroOrOneExpr{
											pos: position{line: 8, col: 38, offset: 109},
											expr: &ruleRefExpr{
												pos:  position{line: 8, col: 38, offset: 109},
												name: "WhiteSpace",
											},
										},
									},
								},
							},
						},
						&ruleRefExpr{
							pos:  position{line: 8, col: 52, offset: 123},
							name: "EOF",
						},
					},
				},
			},
		},
		{
			name: "Statement",
			pos:  position{line: 21, col: 1, offset: 393},
			expr: &choiceExpr{
				pos: position{line: 21, col: 14, offset: 406},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 21, col: 14, offset: 406},
						name: "CreateTable",
					},
					&ruleRefExpr{
						pos:  position{line: 21, col: 28, offset: 420},
						name: "Grant",
					},
				},
			},
		},
		{
			name: "CreateTable",
			pos:  position{line: 24, col: 1, offset: 431},
			expr: &actionExpr{
				pos: position{line: 24, col: 16, offset: 446},
				run: (*parser).callonCreateTable1,
				expr: &seqExpr{
					pos: position{line: 24, col: 16, offset: 446},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 24, col: 16, offset: 446},
							val:        "CREATE",
							ignoreCase: false,
							want:       "\"CREATE\"",
						},
						&zeroOrOneExpr{
							pos: position{line: 24, col: 25, offset: 455},
							expr: &ruleRefExpr{
								pos:  position{line: 24, col: 25, offset: 455},
								name: "WhiteSpace",
							},
						},
						&litMatcher{
							pos:        position{line: 24, col: 37, offset: 467},
							val:        "TABLE",
							ignoreCase: false,
							want:       "\"TABLE\"",
						},
						&ruleRefExpr{
							pos:  position{line: 24, col: 45, offset: 475},
							name: "WhiteSpace",
						},
						&labeledExpr{
							pos:   position{line: 24, col: 56, offset: 486},
							label: "name",
							expr: &ruleRefExpr{
								pos:  position{line: 24, col: 61, offset: 491},
								name: "TableName",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 24, col: 71, offset: 501},
							name: "WhiteSpace",
						},
						&labeledExpr{
							pos:   position{line: 24, col: 82, offset: 512},
							label: "body",
							expr: &ruleRefExpr{
								pos:  position{line: 24, col: 87, offset: 517},
								name: "TableBody",
							},
						},
						&ruleRefExpr{
							pos:  position{line: 24, col: 97, offset: 527},
							name: "IgnoreTableEndParams",
						},
						&litMatcher{
							pos:        position{line: 24, col: 118, offset: 548},
							val:        ";",
							ignoreCase: false,
							want:       "\";\"",
						},
					},
				},
			},
		},
		{
			name: "Grant",
			pos:  position{line: 40, col: 1, offset: 809},
			expr: &actionExpr{
				pos: position{line: 40, col: 10, offset: 818},
				run: (*parser).callonGrant1,
				expr: &seqExpr{
					pos: position{line: 40, col: 10, offset: 818},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 40, col: 10, offset: 818},
							val:        "GRANT",
							ignoreCase: false,
							want:       "\"GRANT\"",
						},
						&zeroOrOneExpr{
							pos: position{line: 40, col: 18, offset: 826},
							expr: &ruleRefExpr{
								pos:  position{line: 40, col: 18, offset: 826},
								name: "WhiteSpace",
							},
						},
						&labeledExpr{
							pos:   position{line: 40, col: 30, offset: 838},
							label: "grantType",
							expr: &ruleRefExpr{
								pos:  position{line: 40, col: 40, offset: 848},
								name: "GrantType",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 40, col: 50, offset: 858},
							expr: &ruleRefExpr{
								pos:  position{line: 40, col: 50, offset: 858},
								name: "WhiteSpace",
							},
						},
						&litMatcher{
							pos:        position{line: 40, col: 62, offset: 870},
							val:        "ON",
							ignoreCase: false,
							want:       "\"ON\"",
						},
						&zeroOrOneExpr{
							pos: position{line: 40, col: 67, offset: 875},
							expr: &ruleRefExpr{
								pos:  position{line: 40, col: 67, offset: 875},
								name: "WhiteSpace",
							},
						},
						&labeledExpr{
							pos:   position{line: 40, col: 79, offset: 887},
							label: "grantWhere",
							expr: &ruleRefExpr{
								pos:  position{line: 40, col: 90, offset: 898},
								name: "TableName",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 40, col: 100, offset: 908},
							expr: &ruleRefExpr{
								pos:  position{line: 40, col: 100, offset: 908},
								name: "WhiteSpace",
							},
						},
						&litMatcher{
							pos:        position{line: 40, col: 112, offset: 920},
							val:        "TO",
							ignoreCase: false,
							want:       "\"TO\"",
						},
						&zeroOrOneExpr{
							pos: position{line: 40, col: 117, offset: 925},
							expr: &ruleRefExpr{
								pos:  position{line: 40, col: 117, offset: 925},
								name: "WhiteSpace",
							},
						},
						&labeledExpr{
							pos:   position{line: 40, col: 129, offset: 937},
							label: "grantWho",
							expr: &ruleRefExpr{
								pos:  position{line: 40, col: 138, offset: 946},
								name: "LiteralString",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 40, col: 152, offset: 960},
							expr: &ruleRefExpr{
								pos:  position{line: 40, col: 152, offset: 960},
								name: "WhiteSpace",
							},
						},
						&litMatcher{
							pos:        position{line: 40, col: 164, offset: 972},
							val:        ";",
							ignoreCase: false,
							want:       "\";\"",
						},
					},
				},
			},
		},
		{
			name: "GrantType",
			pos:  position{line: 47, col: 1, offset: 1110},
			expr: &actionExpr{
				pos: position{line: 47, col: 14, offset: 1123},
				run: (*parser).callonGrantType1,
				expr: &choiceExpr{
					pos: position{line: 47, col: 15, offset: 1124},
					alternatives: []any{
						&litMatcher{
							pos:        position{line: 47, col: 15, offset: 1124},
							val:        "UPDATE",
							ignoreCase: false,
							want:       "\"UPDATE\"",
						},
						&litMatcher{
							pos:        position{line: 47, col: 26, offset: 1135},
							val:        "SELECT",
							ignoreCase: false,
							want:       "\"SELECT\"",
						},
						&litMatcher{
							pos:        position{line: 47, col: 37, offset: 1146},
							val:        "INSERT",
							ignoreCase: false,
							want:       "\"INSERT\"",
						},
					},
				},
			},
		},
		{
			name: "TableName",
			pos:  position{line: 51, col: 1, offset: 1194},
			expr: &actionExpr{
				pos: position{line: 51, col: 14, offset: 1207},
				run: (*parser).callonTableName1,
				expr: &seqExpr{
					pos: position{line: 51, col: 14, offset: 1207},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 51, col: 14, offset: 1207},
							label: "first",
							expr: &ruleRefExpr{
								pos:  position{line: 51, col: 20, offset: 1213},
								name: "TableNamePart",
							},
						},
						&labeledExpr{
							pos:   position{line: 51, col: 34, offset: 1227},
							label: "second",
							expr: &zeroOrOneExpr{
								pos: position{line: 51, col: 41, offset: 1234},
								expr: &seqExpr{
									pos: position{line: 51, col: 42, offset: 1235},
									exprs: []any{
										&litMatcher{
											pos:        position{line: 51, col: 42, offset: 1235},
											val:        ".",
											ignoreCase: false,
											want:       "\".\"",
										},
										&labeledExpr{
											pos:   position{line: 51, col: 46, offset: 1239},
											label: "t",
											expr: &ruleRefExpr{
												pos:  position{line: 51, col: 48, offset: 1241},
												name: "TableNamePart",
											},
										},
									},
								},
							},
						},
					},
				},
			},
		},
		{
			name: "TableNamePart",
			pos:  position{line: 61, col: 1, offset: 1565},
			expr: &choiceExpr{
				pos: position{line: 61, col: 18, offset: 1582},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 61, col: 18, offset: 1582},
						name: "LiteralString",
					},
					&actionExpr{
						pos: position{line: 61, col: 34, offset: 1598},
						run: (*parser).callonTableNamePart3,
						expr: &ruleRefExpr{
							pos:  position{line: 61, col: 34, offset: 1598},
							name: "Identifier",
						},
					},
				},
			},
		},
		{
			name: "TableBody",
			pos:  position{line: 65, col: 1, offset: 1647},
			expr: &ruleRefExpr{
				pos:  position{line: 65, col: 14, offset: 1660},
				name: "TableBodyDef",
			},
		},
		{
			name: "TableBodyDef",
			pos:  position{line: 67, col: 1, offset: 1697},
			expr: &actionExpr{
				pos: position{line: 67, col: 17, offset: 1713},
				run: (*parser).callonTableBodyDef1,
				expr: &seqExpr{
					pos: position{line: 67, col: 17, offset: 1713},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 67, col: 17, offset: 1713},
							val:        "(",
							ignoreCase: false,
							want:       "\"(\"",
						},
						&zeroOrOneExpr{
							pos: position{line: 67, col: 21, offset: 1717},
							expr: &ruleRefExpr{
								pos:  position{line: 67, col: 21, offset: 1717},
								name: "WhiteSpace",
							},
						},
						&labeledExpr{
							pos:   position{line: 67, col: 33, offset: 1729},
							label: "cols",
							expr: &ruleRefExpr{
								pos:  position{line: 67, col: 38, offset: 1734},
								name: "Columns",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 67, col: 46, offset: 1742},
							expr: &ruleRefExpr{
								pos:  position{line: 67, col: 46, offset: 1742},
								name: "WhiteSpace",
							},
						},
						&litMatcher{
							pos:        position{line: 67, col: 58, offset: 1754},
							val:        ")",
							ignoreCase: false,
							want:       "\")\"",
						},
					},
				},
			},
		},
		{
			name: "Columns",
			pos:  position{line: 71, col: 1, offset: 1786},
			expr: &actionExpr{
				pos: position{line: 71, col: 12, offset: 1797},
				run: (*parser).callonColumns1,
				expr: &labeledExpr{
					pos:   position{line: 71, col: 12, offset: 1797},
					label: "items",
					expr: &zeroOrMoreExpr{
						pos: position{line: 71, col: 18, offset: 1803},
						expr: &seqExpr{
							pos: position{line: 71, col: 19, offset: 1804},
							exprs: []any{
								&zeroOrOneExpr{
									pos: position{line: 71, col: 19, offset: 1804},
									expr: &ruleRefExpr{
										pos:  position{line: 71, col: 19, offset: 1804},
										name: "WhiteSpace",
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 71, col: 31, offset: 1816},
									expr: &litMatcher{
										pos:        position{line: 71, col: 31, offset: 1816},
										val:        ",",
										ignoreCase: false,
										want:       "\",\"",
									},
								},
								&zeroOrOneExpr{
									pos: position{line: 71, col: 36, offset: 1821},
									expr: &ruleRefExpr{
										pos:  position{line: 71, col: 36, offset: 1821},
										name: "WhiteSpace",
									},
								},
								&ruleRefExpr{
									pos:  position{line: 71, col: 48, offset: 1833},
									name: "Column",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Column",
			pos:  position{line: 95, col: 1, offset: 2238},
			expr: &actionExpr{
				pos: position{line: 95, col: 11, offset: 2248},
				run: (*parser).callonColumn1,
				expr: &seqExpr{
					pos: position{line: 95, col: 11, offset: 2248},
					exprs: []any{
						&labeledExpr{
							pos:   position{line: 95, col: 11, offset: 2248},
							label: "colname",
							expr: &ruleRefExpr{
								pos:  position{line: 95, col: 19, offset: 2256},
								name: "ColumnName",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 95, col: 30, offset: 2267},
							expr: &ruleRefExpr{
								pos:  position{line: 95, col: 30, offset: 2267},
								name: "WhiteSpace",
							},
						},
						&labeledExpr{
							pos:   position{line: 95, col: 42, offset: 2279},
							label: "coltype",
							expr: &ruleRefExpr{
								pos:  position{line: 95, col: 50, offset: 2287},
								name: "ColumnType",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 95, col: 61, offset: 2298},
							expr: &ruleRefExpr{
								pos:  position{line: 95, col: 61, offset: 2298},
								name: "WhiteSpace",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 95, col: 73, offset: 2310},
							expr: &ruleRefExpr{
								pos:  position{line: 95, col: 73, offset: 2310},
								name: "ColumnTypeArgs",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 95, col: 89, offset: 2326},
							expr: &ruleRefExpr{
								pos:  position{line: 95, col: 89, offset: 2326},
								name: "WhiteSpace",
							},
						},
						&zeroOrOneExpr{
							pos: position{line: 95, col: 101, offset: 2338},
							expr: &ruleRefExpr{
								pos:  position{line: 95, col: 101, offset: 2338},
								name: "ColumnDefault",
							},
						},
					},
				},
			},
		},
		{
			name: "ColumnDefault",
			pos:  position{line: 106, col: 1, offset: 2545},
			expr: &seqExpr{
				pos: position{line: 106, col: 18, offset: 2562},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 106, col: 18, offset: 2562},
						val:        "DEFAULT",
						ignoreCase: false,
						want:       "\"DEFAULT\"",
					},
					&zeroOrOneExpr{
						pos: position{line: 106, col: 28, offset: 2572},
						expr: &ruleRefExpr{
							pos:  position{line: 106, col: 28, offset: 2572},
							name: "WhiteSpace",
						},
					},
					&zeroOrOneExpr{
						pos: position{line: 106, col: 40, offset: 2584},
						expr: &ruleRefExpr{
							pos:  position{line: 106, col: 40, offset: 2584},
							name: "LiteralValue",
						},
					},
				},
			},
		},
		{
			name: "ColumnType",
			pos:  position{line: 108, col: 1, offset: 2601},
			expr: &actionExpr{
				pos: position{line: 108, col: 15, offset: 2615},
				run: (*parser).callonColumnType1,
				expr: &choiceExpr{
					pos: position{line: 108, col: 16, offset: 2616},
					alternatives: []any{
						&litMatcher{
							pos:        position{line: 108, col: 16, offset: 2616},
							val:        "CHAR",
							ignoreCase: false,
							want:       "\"CHAR\"",
						},
						&litMatcher{
							pos:        position{line: 108, col: 25, offset: 2625},
							val:        "CLOB",
							ignoreCase: false,
							want:       "\"CLOB\"",
						},
						&litMatcher{
							pos:        position{line: 108, col: 34, offset: 2634},
							val:        "DATE",
							ignoreCase: false,
							want:       "\"DATE\"",
						},
						&litMatcher{
							pos:        position{line: 108, col: 43, offset: 2643},
							val:        "INT",
							ignoreCase: false,
							want:       "\"INT\"",
						},
						&litMatcher{
							pos:        position{line: 108, col: 51, offset: 2651},
							val:        "NUMBER",
							ignoreCase: false,
							want:       "\"NUMBER\"",
						},
						&litMatcher{
							pos:        position{line: 108, col: 62, offset: 2662},
							val:        "NUMERICAL",
							ignoreCase: false,
							want:       "\"NUMERICAL\"",
						},
						&litMatcher{
							pos:        position{line: 108, col: 76, offset: 2676},
							val:        "DECIMAL",
							ignoreCase: false,
							want:       "\"DECIMAL\"",
						},
						&litMatcher{
							pos:        position{line: 108, col: 88, offset: 2688},
							val:        "VARCHAR2",
							ignoreCase: false,
							want:       "\"VARCHAR2\"",
						},
						&litMatcher{
							pos:        position{line: 108, col: 101, offset: 2701},
							val:        "VARCHAR",
							ignoreCase: false,
							want:       "\"VARCHAR\"",
						},
					},
				},
			},
		},
		{
			name: "ColumnTypeArgs",
			pos:  position{line: 112, col: 1, offset: 2750},
			expr: &seqExpr{
				pos: position{line: 112, col: 19, offset: 2768},
				exprs: []any{
					&litMatcher{
						pos:        position{line: 112, col: 19, offset: 2768},
						val:        "(",
						ignoreCase: false,
						want:       "\"(\"",
					},
					&zeroOrOneExpr{
						pos: position{line: 112, col: 23, offset: 2772},
						expr: &ruleRefExpr{
							pos:  position{line: 112, col: 23, offset: 2772},
							name: "WhiteSpace",
						},
					},
					&zeroOrMoreExpr{
						pos: position{line: 112, col: 35, offset: 2784},
						expr: &charClassMatcher{
							pos:        position{line: 112, col: 35, offset: 2784},
							val:        "[0-9,]",
							chars:      []rune{','},
							ranges:     []rune{'0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&zeroOrOneExpr{
						pos: position{line: 112, col: 43, offset: 2792},
						expr: &ruleRefExpr{
							pos:  position{line: 112, col: 43, offset: 2792},
							name: "WhiteSpace",
						},
					},
					&zeroOrOneExpr{
						pos: position{line: 112, col: 55, offset: 2804},
						expr: &ruleRefExpr{
							pos:  position{line: 112, col: 55, offset: 2804},
							name: "ColumnTypeKeyword",
						},
					},
					&zeroOrOneExpr{
						pos: position{line: 112, col: 74, offset: 2823},
						expr: &ruleRefExpr{
							pos:  position{line: 112, col: 74, offset: 2823},
							name: "WhiteSpace",
						},
					},
					&litMatcher{
						pos:        position{line: 112, col: 86, offset: 2835},
						val:        ")",
						ignoreCase: false,
						want:       "\")\"",
					},
				},
			},
		},
		{
			name: "ColumnTypeKeyword",
			pos:  position{line: 114, col: 1, offset: 2842},
			expr: &litMatcher{
				pos:        position{line: 114, col: 22, offset: 2863},
				val:        "BYTE",
				ignoreCase: false,
				want:       "\"BYTE\"",
			},
		},
		{
			name: "IgnoreTableEndParams",
			pos:  position{line: 116, col: 1, offset: 2873},
			expr: &zeroOrMoreExpr{
				pos: position{line: 116, col: 25, offset: 2897},
				expr: &seqExpr{
					pos: position{line: 116, col: 26, offset: 2898},
					exprs: []any{
						&notExpr{
							pos: position{line: 116, col: 26, offset: 2898},
							expr: &litMatcher{
								pos:        position{line: 116, col: 27, offset: 2899},
								val:        ";",
								ignoreCase: false,
								want:       "\";\"",
							},
						},
						&anyMatcher{
							line: 116, col: 31, offset: 2903,
						},
					},
				},
			},
		},
		{
			name: "ColumnName",
			pos:  position{line: 123, col: 1, offset: 2994},
			expr: &ruleRefExpr{
				pos:  position{line: 123, col: 15, offset: 3008},
				name: "LiteralString",
			},
		},
		{
			name: "Identifier",
			pos:  position{line: 125, col: 1, offset: 3025},
			expr: &seqExpr{
				pos: position{line: 125, col: 15, offset: 3039},
				exprs: []any{
					&charClassMatcher{
						pos:        position{line: 125, col: 15, offset: 3039},
						val:        "[a-zA-Z_]",
						chars:      []rune{'_'},
						ranges:     []rune{'a', 'z', 'A', 'Z'},
						ignoreCase: false,
						inverted:   false,
					},
					&oneOrMoreExpr{
						pos: position{line: 125, col: 24, offset: 3048},
						expr: &charClassMatcher{
							pos:        position{line: 125, col: 24, offset: 3048},
							val:        "[a-zA-Z0-9_]",
							chars:      []rune{'_'},
							ranges:     []rune{'a', 'z', 'A', 'Z', '0', '9'},
							ignoreCase: false,
							inverted:   false,
						},
					},
				},
			},
		},
		{
			name: "LiteralValue",
			pos:  position{line: 127, col: 1, offset: 3065},
			expr: &choiceExpr{
				pos: position{line: 127, col: 17, offset: 3081},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 127, col: 17, offset: 3081},
						name: "LiteralString",
					},
					&ruleRefExpr{
						pos:  position{line: 127, col: 33, offset: 3097},
						name: "LiteralNumber",
					},
				},
			},
		},
		{
			name: "LiteralNumber",
			pos:  position{line: 129, col: 1, offset: 3114},
			expr: &seqExpr{
				pos: position{line: 129, col: 18, offset: 3131},
				exprs: []any{
					&zeroOrOneExpr{
						pos: position{line: 129, col: 18, offset: 3131},
						expr: &ruleRefExpr{
							pos:  position{line: 129, col: 18, offset: 3131},
							name: "Sign",
						},
					},
					&choiceExpr{
						pos: position{line: 129, col: 25, offset: 3138},
						alternatives: []any{
							&ruleRefExpr{
								pos:  position{line: 129, col: 25, offset: 3138},
								name: "Float",
							},
							&ruleRefExpr{
								pos:  position{line: 129, col: 33, offset: 3146},
								name: "Integer",
							},
						},
					},
				},
			},
		},
		{
			name: "Sign",
			pos:  position{line: 130, col: 1, offset: 3156},
			expr: &charClassMatcher{
				pos:        position{line: 130, col: 9, offset: 3164},
				val:        "[+-]",
				chars:      []rune{'+', '-'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "Float",
			pos:  position{line: 131, col: 1, offset: 3170},
			expr: &choiceExpr{
				pos: position{line: 131, col: 10, offset: 3179},
				alternatives: []any{
					&seqExpr{
						pos: position{line: 131, col: 10, offset: 3179},
						exprs: []any{
							&zeroOrOneExpr{
								pos: position{line: 131, col: 10, offset: 3179},
								expr: &ruleRefExpr{
									pos:  position{line: 131, col: 10, offset: 3179},
									name: "Digits",
								},
							},
							&litMatcher{
								pos:        position{line: 131, col: 18, offset: 3187},
								val:        ".",
								ignoreCase: false,
								want:       "\".\"",
							},
							&ruleRefExpr{
								pos:  position{line: 131, col: 22, offset: 3191},
								name: "Digits",
							},
							&zeroOrOneExpr{
								pos: position{line: 131, col: 29, offset: 3198},
								expr: &ruleRefExpr{
									pos:  position{line: 131, col: 30, offset: 3199},
									name: "ExponentPart",
								},
							},
						},
					},
					&seqExpr{
						pos: position{line: 131, col: 47, offset: 3216},
						exprs: []any{
							&ruleRefExpr{
								pos:  position{line: 131, col: 47, offset: 3216},
								name: "Digits",
							},
							&litMatcher{
								pos:        position{line: 131, col: 54, offset: 3223},
								val:        ".",
								ignoreCase: false,
								want:       "\".\"",
							},
							&zeroOrOneExpr{
								pos: position{line: 131, col: 58, offset: 3227},
								expr: &ruleRefExpr{
									pos:  position{line: 131, col: 59, offset: 3228},
									name: "ExponentPart",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "Integer",
			pos:  position{line: 132, col: 1, offset: 3244},
			expr: &seqExpr{
				pos: position{line: 132, col: 12, offset: 3255},
				exprs: []any{
					&ruleRefExpr{
						pos:  position{line: 132, col: 12, offset: 3255},
						name: "Digits",
					},
					&zeroOrOneExpr{
						pos: position{line: 132, col: 19, offset: 3262},
						expr: &ruleRefExpr{
							pos:  position{line: 132, col: 20, offset: 3263},
							name: "ExponentPart",
						},
					},
				},
			},
		},
		{
			name: "ExponentPart",
			pos:  position{line: 133, col: 1, offset: 3279},
			expr: &seqExpr{
				pos: position{line: 133, col: 17, offset: 3295},
				exprs: []any{
					&charClassMatcher{
						pos:        position{line: 133, col: 17, offset: 3295},
						val:        "[eE]",
						chars:      []rune{'e', 'E'},
						ignoreCase: false,
						inverted:   false,
					},
					&zeroOrOneExpr{
						pos: position{line: 133, col: 22, offset: 3300},
						expr: &charClassMatcher{
							pos:        position{line: 133, col: 22, offset: 3300},
							val:        "[+-]",
							chars:      []rune{'+', '-'},
							ignoreCase: false,
							inverted:   false,
						},
					},
					&ruleRefExpr{
						pos:  position{line: 133, col: 28, offset: 3306},
						name: "Digits",
					},
				},
			},
		},
		{
			name: "Digits",
			pos:  position{line: 134, col: 1, offset: 3314},
			expr: &oneOrMoreExpr{
				pos: position{line: 134, col: 11, offset: 3324},
				expr: &charClassMatcher{
					pos:        position{line: 134, col: 11, offset: 3324},
					val:        "[0-9]",
					ranges:     []rune{'0', '9'},
					ignoreCase: false,
					inverted:   false,
				},
			},
		},
		{
			name: "LiteralString",
			pos:  position{line: 136, col: 1, offset: 3334},
			expr: &choiceExpr{
				pos: position{line: 136, col: 18, offset: 3351},
				alternatives: []any{
					&ruleRefExpr{
						pos:  position{line: 136, col: 18, offset: 3351},
						name: "LiteralStringSingleQuote",
					},
					&ruleRefExpr{
						pos:  position{line: 136, col: 45, offset: 3378},
						name: "LiteralStringDoubleQuote",
					},
				},
			},
		},
		{
			name: "LiteralStringSingleQuote",
			pos:  position{line: 137, col: 1, offset: 3404},
			expr: &actionExpr{
				pos: position{line: 137, col: 29, offset: 3432},
				run: (*parser).callonLiteralStringSingleQuote1,
				expr: &seqExpr{
					pos: position{line: 137, col: 29, offset: 3432},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 137, col: 29, offset: 3432},
							val:        "'",
							ignoreCase: false,
							want:       "\"'\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 137, col: 34, offset: 3437},
							expr: &seqExpr{
								pos: position{line: 137, col: 35, offset: 3438},
								exprs: []any{
									&notExpr{
										pos: position{line: 137, col: 35, offset: 3438},
										expr: &litMatcher{
											pos:        position{line: 137, col: 36, offset: 3439},
											val:        "'",
											ignoreCase: false,
											want:       "\"'\"",
										},
									},
									&anyMatcher{
										line: 137, col: 41, offset: 3444,
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 137, col: 45, offset: 3448},
							val:        "'",
							ignoreCase: false,
							want:       "\"'\"",
						},
					},
				},
			},
		},
		{
			name: "LiteralStringDoubleQuote",
			pos:  position{line: 141, col: 1, offset: 3526},
			expr: &actionExpr{
				pos: position{line: 141, col: 29, offset: 3554},
				run: (*parser).callonLiteralStringDoubleQuote1,
				expr: &seqExpr{
					pos: position{line: 141, col: 29, offset: 3554},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 141, col: 29, offset: 3554},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 141, col: 33, offset: 3558},
							expr: &seqExpr{
								pos: position{line: 141, col: 34, offset: 3559},
								exprs: []any{
									&notExpr{
										pos: position{line: 141, col: 34, offset: 3559},
										expr: &litMatcher{
											pos:        position{line: 141, col: 35, offset: 3560},
											val:        "\"",
											ignoreCase: false,
											want:       "\"\\\"\"",
										},
									},
									&anyMatcher{
										line: 141, col: 39, offset: 3564,
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 141, col: 43, offset: 3568},
							val:        "\"",
							ignoreCase: false,
							want:       "\"\\\"\"",
						},
					},
				},
			},
		},
		{
			name: "WhiteSpace",
			pos:  position{line: 146, col: 1, offset: 3647},
			expr: &oneOrMoreExpr{
				pos: position{line: 146, col: 15, offset: 3661},
				expr: &choiceExpr{
					pos: position{line: 146, col: 16, offset: 3662},
					alternatives: []any{
						&ruleRefExpr{
							pos:  position{line: 146, col: 16, offset: 3662},
							name: "Spaces",
						},
						&ruleRefExpr{
							pos:  position{line: 146, col: 25, offset: 3671},
							name: "NewLines",
						},
						&ruleRefExpr{
							pos:  position{line: 146, col: 36, offset: 3682},
							name: "LineComment",
						},
						&ruleRefExpr{
							pos:  position{line: 146, col: 50, offset: 3696},
							name: "BlockComment",
						},
					},
				},
			},
		},
		{
			name: "Spaces",
			pos:  position{line: 147, col: 1, offset: 3712},
			expr: &actionExpr{
				pos: position{line: 147, col: 11, offset: 3722},
				run: (*parser).callonSpaces1,
				expr: &oneOrMoreExpr{
					pos: position{line: 147, col: 11, offset: 3722},
					expr: &ruleRefExpr{
						pos:  position{line: 147, col: 11, offset: 3722},
						name: "Space",
					},
				},
			},
		},
		{
			name: "Space",
			pos:  position{line: 150, col: 1, offset: 3754},
			expr: &charClassMatcher{
				pos:        position{line: 150, col: 10, offset: 3763},
				val:        "[ \\t]",
				chars:      []rune{' ', '\t'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "NewLines",
			pos:  position{line: 151, col: 1, offset: 3770},
			expr: &actionExpr{
				pos: position{line: 151, col: 13, offset: 3782},
				run: (*parser).callonNewLines1,
				expr: &oneOrMoreExpr{
					pos: position{line: 151, col: 13, offset: 3782},
					expr: &ruleRefExpr{
						pos:  position{line: 151, col: 13, offset: 3782},
						name: "NewLine",
					},
				},
			},
		},
		{
			name: "NewLine",
			pos:  position{line: 154, col: 1, offset: 3816},
			expr: &charClassMatcher{
				pos:        position{line: 154, col: 12, offset: 3827},
				val:        "[ \\r\\n]",
				chars:      []rune{' ', '\r', '\n'},
				ignoreCase: false,
				inverted:   false,
			},
		},
		{
			name: "LineComment",
			pos:  position{line: 155, col: 1, offset: 3836},
			expr: &actionExpr{
				pos: position{line: 155, col: 16, offset: 3851},
				run: (*parser).callonLineComment1,
				expr: &seqExpr{
					pos: position{line: 155, col: 16, offset: 3851},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 155, col: 16, offset: 3851},
							val:        "--",
							ignoreCase: false,
							want:       "\"--\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 155, col: 21, offset: 3856},
							expr: &seqExpr{
								pos: position{line: 155, col: 22, offset: 3857},
								exprs: []any{
									&notExpr{
										pos: position{line: 155, col: 22, offset: 3857},
										expr: &charClassMatcher{
											pos:        position{line: 155, col: 23, offset: 3858},
											val:        "[\\r\\n]",
											chars:      []rune{'\r', '\n'},
											ignoreCase: false,
											inverted:   false,
										},
									},
									&anyMatcher{
										line: 155, col: 30, offset: 3865,
									},
								},
							},
						},
						&choiceExpr{
							pos: position{line: 155, col: 35, offset: 3870},
							alternatives: []any{
								&seqExpr{
									pos: position{line: 155, col: 35, offset: 3870},
									exprs: []any{
										&zeroOrOneExpr{
											pos: position{line: 155, col: 35, offset: 3870},
											expr: &litMatcher{
												pos:        position{line: 155, col: 35, offset: 3870},
												val:        "\r",
												ignoreCase: false,
												want:       "\"\\r\"",
											},
										},
										&litMatcher{
											pos:        position{line: 155, col: 41, offset: 3876},
											val:        "\n",
											ignoreCase: false,
											want:       "\"\\n\"",
										},
									},
								},
								&ruleRefExpr{
									pos:  position{line: 155, col: 48, offset: 3883},
									name: "EOF",
								},
							},
						},
					},
				},
			},
		},
		{
			name: "BlockComment",
			pos:  position{line: 158, col: 1, offset: 3912},
			expr: &actionExpr{
				pos: position{line: 158, col: 17, offset: 3928},
				run: (*parser).callonBlockComment1,
				expr: &seqExpr{
					pos: position{line: 158, col: 17, offset: 3928},
					exprs: []any{
						&litMatcher{
							pos:        position{line: 158, col: 17, offset: 3928},
							val:        "/*",
							ignoreCase: false,
							want:       "\"/*\"",
						},
						&zeroOrMoreExpr{
							pos: position{line: 158, col: 22, offset: 3933},
							expr: &seqExpr{
								pos: position{line: 158, col: 23, offset: 3934},
								exprs: []any{
									&notExpr{
										pos: position{line: 158, col: 23, offset: 3934},
										expr: &litMatcher{
											pos:        position{line: 158, col: 24, offset: 3935},
											val:        "*/",
											ignoreCase: false,
											want:       "\"*/\"",
										},
									},
									&anyMatcher{
										line: 158, col: 29, offset: 3940,
									},
								},
							},
						},
						&litMatcher{
							pos:        position{line: 158, col: 33, offset: 3944},
							val:        "*/",
							ignoreCase: false,
							want:       "\"*/\"",
						},
					},
				},
			},
		},
		{
			name: "EOF",
			pos:  position{line: 162, col: 1, offset: 3975},
			expr: &notExpr{
				pos: position{line: 162, col: 8, offset: 3982},
				expr: &anyMatcher{
					line: 162, col: 9, offset: 3983,
				},
			},
		},
	},
}

func (c *current) onFile1(stmts any) (any, error) {

	var res []any
	//for each pair in stmts
	for _, stmt := range stmts.([]any) {
		pair := stmt.([]any)
		// pair[1] is WhiteSpace and we don't care about it
		if pair[0] != nil {
			res = append(res, pair[0])
		}
	}
	return res, nil
}

func (p *parser) callonFile1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onFile1(stack["stmts"])
}

func (c *current) onCreateTable1(name, body any) (any, error) {

	result := generic.TableDef{
		Name:    name.(string),
		Columns: nil,
	}

	switch b := body.(type) {
	case generic.ColumnsDef:
		result.Columns = b
	case string:
		result.SelectStatement = b
	}

	return result, nil
}

func (p *parser) callonCreateTable1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onCreateTable1(stack["name"], stack["body"])
}

func (c *current) onGrant1(grantType, grantWhere, grantWho any) (any, error) {

	return generic.Grant{
		Type:  grantType.(string),
		Where: grantWhere.(string),
		Who:   grantWho.(string),
	}, nil
}

func (p *parser) callonGrant1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGrant1(stack["grantType"], stack["grantWhere"], stack["grantWho"])
}

func (c *current) onGrantType1() (any, error) {

	return string(c.text), nil
}

func (p *parser) callonGrantType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onGrantType1()
}

func (c *current) onTableName1(first, second any) (any, error) {

	name := first.(string)
	if second != nil {
		// second is []any{ "." as []uint8, t as string }
		parts := second.([]any)
		dot := string(parts[0].([]uint8)) // literal "." match
		name += dot + parts[1].(string)   // append second part
	}
	return name, nil
}

func (p *parser) callonTableName1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTableName1(stack["first"], stack["second"])
}

func (c *current) onTableNamePart3() (any, error) {

	return string(c.text), nil
}

func (p *parser) callonTableNamePart3() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTableNamePart3()
}

func (c *current) onTableBodyDef1(cols any) (any, error) {

	return cols, nil
}

func (p *parser) callonTableBodyDef1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onTableBodyDef1(stack["cols"])
}

func (c *current) onColumns1(items any) (any, error) {

	results := generic.ColumnsDef{}

	for _, item := range items.([]any) {
		if item == nil {
			continue
		}

		for _, subitem := range item.([]any) {
			if subitem == nil {
				continue
			}

			switch column := subitem.(type) {
			case *generic.ColumnDef:
				results[column.Name] = column
			}
		}

	}

	return results, nil
}

func (p *parser) callonColumns1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onColumns1(stack["items"])
}

func (c *current) onColumn1(colname, coltype any) (any, error) {

	result := &generic.ColumnDef{
		Name: colname.(string),
		Type: coltype.(string),
		//Default   string
		//Precision int
		//Scale     int
	}
	return result, nil
}

func (p *parser) callonColumn1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onColumn1(stack["colname"], stack["coltype"])
}

func (c *current) onColumnType1() (any, error) {

	return string(c.text), nil
}

func (p *parser) callonColumnType1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onColumnType1()
}

func (c *current) onLiteralStringSingleQuote1() (any, error) {

	s := string(c.text)
	return s[1 : len(s)-1], nil //strip quotes
}

func (p *parser) callonLiteralStringSingleQuote1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLiteralStringSingleQuote1()
}

func (c *current) onLiteralStringDoubleQuote1() (any, error) {

	s := string(c.text)
	return s[1 : len(s)-1], nil //strip quotes
}

func (p *parser) callonLiteralStringDoubleQuote1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLiteralStringDoubleQuote1()
}

func (c *current) onSpaces1() (any, error) {

	return nil, nil
}

func (p *parser) callonSpaces1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onSpaces1()
}

func (c *current) onNewLines1() (any, error) {

	return nil, nil
}

func (p *parser) callonNewLines1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onNewLines1()
}

func (c *current) onLineComment1() (any, error) {

	return "", nil
}

func (p *parser) callonLineComment1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onLineComment1()
}

func (c *current) onBlockComment1() (any, error) {

	return "", nil
}

func (p *parser) callonBlockComment1() (any, error) {
	stack := p.vstack[len(p.vstack)-1]
	_ = stack
	return p.cur.onBlockComment1()
}

var (
	// errNoRule is returned when the grammar to parse has no rule.
	errNoRule = errors.New("grammar has no rule")

	// errInvalidEntrypoint is returned when the specified entrypoint rule
	// does not exit.
	errInvalidEntrypoint = errors.New("invalid entrypoint")

	// errInvalidEncoding is returned when the source is not properly
	// utf8-encoded.
	errInvalidEncoding = errors.New("invalid encoding")

	// errMaxExprCnt is used to signal that the maximum number of
	// expressions have been parsed.
	errMaxExprCnt = errors.New("max number of expressions parsed")
)

// Option is a function that can set an option on the parser. It returns
// the previous setting as an Option.
type Option func(*parser) Option

// MaxExpressions creates an Option to stop parsing after the provided
// number of expressions have been parsed, if the value is 0 then the parser will
// parse for as many steps as needed (possibly an infinite number).
//
// The default for maxExprCnt is 0.
func MaxExpressions(maxExprCnt uint64) Option {
	return func(p *parser) Option {
		oldMaxExprCnt := p.maxExprCnt
		p.maxExprCnt = maxExprCnt
		return MaxExpressions(oldMaxExprCnt)
	}
}

// Entrypoint creates an Option to set the rule name to use as entrypoint.
// The rule name must have been specified in the -alternate-entrypoints
// if generating the parser with the -optimize-grammar flag, otherwise
// it may have been optimized out. Passing an empty string sets the
// entrypoint to the first rule in the grammar.
//
// The default is to start parsing at the first rule in the grammar.
func Entrypoint(ruleName string) Option {
	return func(p *parser) Option {
		oldEntrypoint := p.entrypoint
		p.entrypoint = ruleName
		if ruleName == "" {
			p.entrypoint = g.rules[0].name
		}
		return Entrypoint(oldEntrypoint)
	}
}

// Statistics adds a user provided Stats struct to the parser to allow
// the user to process the results after the parsing has finished.
// Also the key for the "no match" counter is set.
//
// Example usage:
//
//	input := "input"
//	stats := Stats{}
//	_, err := Parse("input-file", []byte(input), Statistics(&stats, "no match"))
//	if err != nil {
//	    log.Panicln(err)
//	}
//	b, err := json.MarshalIndent(stats.ChoiceAltCnt, "", "  ")
//	if err != nil {
//	    log.Panicln(err)
//	}
//	fmt.Println(string(b))
func Statistics(stats *Stats, choiceNoMatch string) Option {
	return func(p *parser) Option {
		oldStats := p.Stats
		p.Stats = stats
		oldChoiceNoMatch := p.choiceNoMatch
		p.choiceNoMatch = choiceNoMatch
		if p.Stats.ChoiceAltCnt == nil {
			p.Stats.ChoiceAltCnt = make(map[string]map[string]int)
		}
		return Statistics(oldStats, oldChoiceNoMatch)
	}
}

// Debug creates an Option to set the debug flag to b. When set to true,
// debugging information is printed to stdout while parsing.
//
// The default is false.
func Debug(b bool) Option {
	return func(p *parser) Option {
		old := p.debug
		p.debug = b
		return Debug(old)
	}
}

// Memoize creates an Option to set the memoize flag to b. When set to true,
// the parser will cache all results so each expression is evaluated only
// once. This guarantees linear parsing time even for pathological cases,
// at the expense of more memory and slower times for typical cases.
//
// The default is false.
func Memoize(b bool) Option {
	return func(p *parser) Option {
		old := p.memoize
		p.memoize = b
		return Memoize(old)
	}
}

// AllowInvalidUTF8 creates an Option to allow invalid UTF-8 bytes.
// Every invalid UTF-8 byte is treated as a utf8.RuneError (U+FFFD)
// by character class matchers and is matched by the any matcher.
// The returned matched value, c.text and c.offset are NOT affected.
//
// The default is false.
func AllowInvalidUTF8(b bool) Option {
	return func(p *parser) Option {
		old := p.allowInvalidUTF8
		p.allowInvalidUTF8 = b
		return AllowInvalidUTF8(old)
	}
}

// Recover creates an Option to set the recover flag to b. When set to
// true, this causes the parser to recover from panics and convert it
// to an error. Setting it to false can be useful while debugging to
// access the full stack trace.
//
// The default is true.
func Recover(b bool) Option {
	return func(p *parser) Option {
		old := p.recover
		p.recover = b
		return Recover(old)
	}
}

// GlobalStore creates an Option to set a key to a certain value in
// the globalStore.
func GlobalStore(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.globalStore[key]
		p.cur.globalStore[key] = value
		return GlobalStore(key, old)
	}
}

// InitState creates an Option to set a key to a certain value in
// the global "state" store.
func InitState(key string, value any) Option {
	return func(p *parser) Option {
		old := p.cur.state[key]
		p.cur.state[key] = value
		return InitState(key, old)
	}
}

// ParseFile parses the file identified by filename.
func ParseFile(filename string, opts ...Option) (i any, err error) {
	f, err := os.Open(filename)
	if err != nil {
		return nil, err
	}
	defer func() {
		if closeErr := f.Close(); closeErr != nil {
			err = closeErr
		}
	}()
	return ParseReader(filename, f, opts...)
}

// ParseReader parses the data from r using filename as information in the
// error messages.
func ParseReader(filename string, r io.Reader, opts ...Option) (any, error) {
	b, err := io.ReadAll(r)
	if err != nil {
		return nil, err
	}

	return Parse(filename, b, opts...)
}

// Parse parses the data from b using filename as information in the
// error messages.
func Parse(filename string, b []byte, opts ...Option) (any, error) {
	return newParser(filename, b, opts...).parse(g)
}

// position records a position in the text.
type position struct {
	line, col, offset int
}

func (p position) String() string {
	return strconv.Itoa(p.line) + ":" + strconv.Itoa(p.col) + " [" + strconv.Itoa(p.offset) + "]"
}

// savepoint stores all state required to go back to this point in the
// parser.
type savepoint struct {
	position
	rn rune
	w  int
}

type current struct {
	pos  position // start position of the match
	text []byte   // raw text of the match

	// state is a store for arbitrary key,value pairs that the user wants to be
	// tied to the backtracking of the parser.
	// This is always rolled back if a parsing rule fails.
	state storeDict

	// globalStore is a general store for the user to store arbitrary key-value
	// pairs that they need to manage and that they do not want tied to the
	// backtracking of the parser. This is only modified by the user and never
	// rolled back by the parser. It is always up to the user to keep this in a
	// consistent state.
	globalStore storeDict
}

type storeDict map[string]any

// the AST types...

type grammar struct {
	pos   position
	rules []*rule
}

type rule struct {
	pos         position
	name        string
	displayName string
	expr        any
}

type choiceExpr struct {
	pos          position
	alternatives []any
}

type actionExpr struct {
	pos  position
	expr any
	run  func(*parser) (any, error)
}

type recoveryExpr struct {
	pos          position
	expr         any
	recoverExpr  any
	failureLabel []string
}

type seqExpr struct {
	pos   position
	exprs []any
}

type throwExpr struct {
	pos   position
	label string
}

type labeledExpr struct {
	pos   position
	label string
	expr  any
}

type expr struct {
	pos  position
	expr any
}

type (
	andExpr        expr
	notExpr        expr
	zeroOrOneExpr  expr
	zeroOrMoreExpr expr
	oneOrMoreExpr  expr
)

type ruleRefExpr struct {
	pos  position
	name string
}

type stateCodeExpr struct {
	pos position
	run func(*parser) error
}

type andCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type notCodeExpr struct {
	pos position
	run func(*parser) (bool, error)
}

type litMatcher struct {
	pos        position
	val        string
	ignoreCase bool
	want       string
}

type charClassMatcher struct {
	pos             position
	val             string
	basicLatinChars [128]bool
	chars           []rune
	ranges          []rune
	classes         []*unicode.RangeTable
	ignoreCase      bool
	inverted        bool
}

type anyMatcher position

// errList cumulates the errors found by the parser.
type errList []error

func (e *errList) add(err error) {
	*e = append(*e, err)
}

func (e errList) err() error {
	if len(e) == 0 {
		return nil
	}
	e.dedupe()
	return e
}

func (e *errList) dedupe() {
	var cleaned []error
	set := make(map[string]bool)
	for _, err := range *e {
		if msg := err.Error(); !set[msg] {
			set[msg] = true
			cleaned = append(cleaned, err)
		}
	}
	*e = cleaned
}

func (e errList) Error() string {
	switch len(e) {
	case 0:
		return ""
	case 1:
		return e[0].Error()
	default:
		var buf bytes.Buffer

		for i, err := range e {
			if i > 0 {
				buf.WriteRune('\n')
			}
			buf.WriteString(err.Error())
		}
		return buf.String()
	}
}

// parserError wraps an error with a prefix indicating the rule in which
// the error occurred. The original error is stored in the Inner field.
type parserError struct {
	Inner    error
	pos      position
	prefix   string
	expected []string
}

// Error returns the error message.
func (p *parserError) Error() string {
	return p.prefix + ": " + p.Inner.Error()
}

// newParser creates a parser with the specified input source and options.
func newParser(filename string, b []byte, opts ...Option) *parser {
	stats := Stats{
		ChoiceAltCnt: make(map[string]map[string]int),
	}

	p := &parser{
		filename: filename,
		errs:     new(errList),
		data:     b,
		pt:       savepoint{position: position{line: 1}},
		recover:  true,
		cur: current{
			state:       make(storeDict),
			globalStore: make(storeDict),
		},
		maxFailPos:      position{col: 1, line: 1},
		maxFailExpected: make([]string, 0, 20),
		Stats:           &stats,
		// start rule is rule [0] unless an alternate entrypoint is specified
		entrypoint: g.rules[0].name,
	}
	p.setOptions(opts)

	if p.maxExprCnt == 0 {
		p.maxExprCnt = math.MaxUint64
	}

	return p
}

// setOptions applies the options to the parser.
func (p *parser) setOptions(opts []Option) {
	for _, opt := range opts {
		opt(p)
	}
}

type resultTuple struct {
	v   any
	b   bool
	end savepoint
}

const choiceNoMatch = -1

// Stats stores some statistics, gathered during parsing
type Stats struct {
	// ExprCnt counts the number of expressions processed during parsing
	// This value is compared to the maximum number of expressions allowed
	// (set by the MaxExpressions option).
	ExprCnt uint64

	// ChoiceAltCnt is used to count for each ordered choice expression,
	// which alternative is used how may times.
	// These numbers allow to optimize the order of the ordered choice expression
	// to increase the performance of the parser
	//
	// The outer key of ChoiceAltCnt is composed of the name of the rule as well
	// as the line and the column of the ordered choice.
	// The inner key of ChoiceAltCnt is the number (one-based) of the matching alternative.
	// For each alternative the number of matches are counted. If an ordered choice does not
	// match, a special counter is incremented. The name of this counter is set with
	// the parser option Statistics.
	// For an alternative to be included in ChoiceAltCnt, it has to match at least once.
	ChoiceAltCnt map[string]map[string]int
}

type parser struct {
	filename string
	pt       savepoint
	cur      current

	data []byte
	errs *errList

	depth   int
	recover bool
	debug   bool

	memoize bool
	// memoization table for the packrat algorithm:
	// map[offset in source] map[expression or rule] {value, match}
	memo map[int]map[any]resultTuple

	// rules table, maps the rule identifier to the rule node
	rules map[string]*rule
	// variables stack, map of label to value
	vstack []map[string]any
	// rule stack, allows identification of the current rule in errors
	rstack []*rule

	// parse fail
	maxFailPos            position
	maxFailExpected       []string
	maxFailInvertExpected bool

	// max number of expressions to be parsed
	maxExprCnt uint64
	// entrypoint for the parser
	entrypoint string

	allowInvalidUTF8 bool

	*Stats

	choiceNoMatch string
	// recovery expression stack, keeps track of the currently available recovery expression, these are traversed in reverse
	recoveryStack []map[string]any
}

// push a variable set on the vstack.
func (p *parser) pushV() {
	if cap(p.vstack) == len(p.vstack) {
		// create new empty slot in the stack
		p.vstack = append(p.vstack, nil)
	} else {
		// slice to 1 more
		p.vstack = p.vstack[:len(p.vstack)+1]
	}

	// get the last args set
	m := p.vstack[len(p.vstack)-1]
	if m != nil && len(m) == 0 {
		// empty map, all good
		return
	}

	m = make(map[string]any)
	p.vstack[len(p.vstack)-1] = m
}

// pop a variable set from the vstack.
func (p *parser) popV() {
	// if the map is not empty, clear it
	m := p.vstack[len(p.vstack)-1]
	if len(m) > 0 {
		// GC that map
		p.vstack[len(p.vstack)-1] = nil
	}
	p.vstack = p.vstack[:len(p.vstack)-1]
}

// push a recovery expression with its labels to the recoveryStack
func (p *parser) pushRecovery(labels []string, expr any) {
	if cap(p.recoveryStack) == len(p.recoveryStack) {
		// create new empty slot in the stack
		p.recoveryStack = append(p.recoveryStack, nil)
	} else {
		// slice to 1 more
		p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)+1]
	}

	m := make(map[string]any, len(labels))
	for _, fl := range labels {
		m[fl] = expr
	}
	p.recoveryStack[len(p.recoveryStack)-1] = m
}

// pop a recovery expression from the recoveryStack
func (p *parser) popRecovery() {
	// GC that map
	p.recoveryStack[len(p.recoveryStack)-1] = nil

	p.recoveryStack = p.recoveryStack[:len(p.recoveryStack)-1]
}

func (p *parser) print(prefix, s string) string {
	if !p.debug {
		return s
	}

	fmt.Printf("%s %d:%d:%d: %s [%#U]\n",
		prefix, p.pt.line, p.pt.col, p.pt.offset, s, p.pt.rn)
	return s
}

func (p *parser) printIndent(mark string, s string) string {
	return p.print(strings.Repeat(" ", p.depth)+mark, s)
}

func (p *parser) in(s string) string {
	res := p.printIndent(">", s)
	p.depth++
	return res
}

func (p *parser) out(s string) string {
	p.depth--
	return p.printIndent("<", s)
}

func (p *parser) addErr(err error) {
	p.addErrAt(err, p.pt.position, []string{})
}

func (p *parser) addErrAt(err error, pos position, expected []string) {
	var buf bytes.Buffer
	if p.filename != "" {
		buf.WriteString(p.filename)
	}
	if buf.Len() > 0 {
		buf.WriteString(":")
	}
	buf.WriteString(fmt.Sprintf("%d:%d (%d)", pos.line, pos.col, pos.offset))
	if len(p.rstack) > 0 {
		if buf.Len() > 0 {
			buf.WriteString(": ")
		}
		rule := p.rstack[len(p.rstack)-1]
		if rule.displayName != "" {
			buf.WriteString("rule " + rule.displayName)
		} else {
			buf.WriteString("rule " + rule.name)
		}
	}
	pe := &parserError{Inner: err, pos: pos, prefix: buf.String(), expected: expected}
	p.errs.add(pe)
}

func (p *parser) failAt(fail bool, pos position, want string) {
	// process fail if parsing fails and not inverted or parsing succeeds and invert is set
	if fail == p.maxFailInvertExpected {
		if pos.offset < p.maxFailPos.offset {
			return
		}

		if pos.offset > p.maxFailPos.offset {
			p.maxFailPos = pos
			p.maxFailExpected = p.maxFailExpected[:0]
		}

		if p.maxFailInvertExpected {
			want = "!" + want
		}
		p.maxFailExpected = append(p.maxFailExpected, want)
	}
}

// read advances the parser to the next rune.
func (p *parser) read() {
	p.pt.offset += p.pt.w
	rn, n := utf8.DecodeRune(p.data[p.pt.offset:])
	p.pt.rn = rn
	p.pt.w = n
	p.pt.col++
	if rn == '\n' {
		p.pt.line++
		p.pt.col = 0
	}

	if rn == utf8.RuneError && n == 1 { // see utf8.DecodeRune
		if !p.allowInvalidUTF8 {
			p.addErr(errInvalidEncoding)
		}
	}
}

// restore parser position to the savepoint pt.
func (p *parser) restore(pt savepoint) {
	if p.debug {
		defer p.out(p.in("restore"))
	}
	if pt.offset == p.pt.offset {
		return
	}
	p.pt = pt
}

// Cloner is implemented by any value that has a Clone method, which returns a
// copy of the value. This is mainly used for types which are not passed by
// value (e.g map, slice, chan) or structs that contain such types.
//
// This is used in conjunction with the global state feature to create proper
// copies of the state to allow the parser to properly restore the state in
// the case of backtracking.
type Cloner interface {
	Clone() any
}

var statePool = &sync.Pool{
	New: func() any { return make(storeDict) },
}

func (sd storeDict) Discard() {
	for k := range sd {
		delete(sd, k)
	}
	statePool.Put(sd)
}

// clone and return parser current state.
func (p *parser) cloneState() storeDict {
	if p.debug {
		defer p.out(p.in("cloneState"))
	}

	state := statePool.Get().(storeDict)
	for k, v := range p.cur.state {
		if c, ok := v.(Cloner); ok {
			state[k] = c.Clone()
		} else {
			state[k] = v
		}
	}
	return state
}

// restore parser current state to the state storeDict.
// every restoreState should applied only one time for every cloned state
func (p *parser) restoreState(state storeDict) {
	if p.debug {
		defer p.out(p.in("restoreState"))
	}
	p.cur.state.Discard()
	p.cur.state = state
}

// get the slice of bytes from the savepoint start to the current position.
func (p *parser) sliceFrom(start savepoint) []byte {
	return p.data[start.position.offset:p.pt.position.offset]
}

func (p *parser) getMemoized(node any) (resultTuple, bool) {
	if len(p.memo) == 0 {
		return resultTuple{}, false
	}
	m := p.memo[p.pt.offset]
	if len(m) == 0 {
		return resultTuple{}, false
	}
	res, ok := m[node]
	return res, ok
}

func (p *parser) setMemoized(pt savepoint, node any, tuple resultTuple) {
	if p.memo == nil {
		p.memo = make(map[int]map[any]resultTuple)
	}
	m := p.memo[pt.offset]
	if m == nil {
		m = make(map[any]resultTuple)
		p.memo[pt.offset] = m
	}
	m[node] = tuple
}

func (p *parser) buildRulesTable(g *grammar) {
	p.rules = make(map[string]*rule, len(g.rules))
	for _, r := range g.rules {
		p.rules[r.name] = r
	}
}

func (p *parser) parse(g *grammar) (val any, err error) {
	if len(g.rules) == 0 {
		p.addErr(errNoRule)
		return nil, p.errs.err()
	}

	// TODO : not super critical but this could be generated
	p.buildRulesTable(g)

	if p.recover {
		// panic can be used in action code to stop parsing immediately
		// and return the panic as an error.
		defer func() {
			if e := recover(); e != nil {
				if p.debug {
					defer p.out(p.in("panic handler"))
				}
				val = nil
				switch e := e.(type) {
				case error:
					p.addErr(e)
				default:
					p.addErr(fmt.Errorf("%v", e))
				}
				err = p.errs.err()
			}
		}()
	}

	startRule, ok := p.rules[p.entrypoint]
	if !ok {
		p.addErr(errInvalidEntrypoint)
		return nil, p.errs.err()
	}

	p.read() // advance to first rune
	val, ok = p.parseRuleWrap(startRule)
	if !ok {
		if len(*p.errs) == 0 {
			// If parsing fails, but no errors have been recorded, the expected values
			// for the farthest parser position are returned as error.
			maxFailExpectedMap := make(map[string]struct{}, len(p.maxFailExpected))
			for _, v := range p.maxFailExpected {
				maxFailExpectedMap[v] = struct{}{}
			}
			expected := make([]string, 0, len(maxFailExpectedMap))
			eof := false
			if _, ok := maxFailExpectedMap["!."]; ok {
				delete(maxFailExpectedMap, "!.")
				eof = true
			}
			for k := range maxFailExpectedMap {
				expected = append(expected, k)
			}
			sort.Strings(expected)
			if eof {
				expected = append(expected, "EOF")
			}
			p.addErrAt(errors.New("no match found, expected: "+listJoin(expected, ", ", "or")), p.maxFailPos, expected)
		}

		return nil, p.errs.err()
	}
	return val, p.errs.err()
}

func listJoin(list []string, sep string, lastSep string) string {
	switch len(list) {
	case 0:
		return ""
	case 1:
		return list[0]
	default:
		return strings.Join(list[:len(list)-1], sep) + " " + lastSep + " " + list[len(list)-1]
	}
}

func (p *parser) parseRuleMemoize(rule *rule) (any, bool) {
	res, ok := p.getMemoized(rule)
	if ok {
		p.restore(res.end)
		return res.v, res.b
	}

	startMark := p.pt
	val, ok := p.parseRule(rule)
	p.setMemoized(startMark, rule, resultTuple{val, ok, p.pt})

	return val, ok
}

func (p *parser) parseRuleWrap(rule *rule) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRule " + rule.name))
	}
	var (
		val       any
		ok        bool
		startMark = p.pt
	)

	if p.memoize {
		val, ok = p.parseRuleMemoize(rule)
	} else {
		val, ok = p.parseRule(rule)
	}

	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(startMark)))
	}
	return val, ok
}

func (p *parser) parseRule(rule *rule) (any, bool) {
	p.rstack = append(p.rstack, rule)
	p.pushV()
	val, ok := p.parseExprWrap(rule.expr)
	p.popV()
	p.rstack = p.rstack[:len(p.rstack)-1]
	return val, ok
}

func (p *parser) parseExprWrap(expr any) (any, bool) {
	var pt savepoint

	if p.memoize {
		res, ok := p.getMemoized(expr)
		if ok {
			p.restore(res.end)
			return res.v, res.b
		}
		pt = p.pt
	}

	val, ok := p.parseExpr(expr)

	if p.memoize {
		p.setMemoized(pt, expr, resultTuple{val, ok, p.pt})
	}
	return val, ok
}

func (p *parser) parseExpr(expr any) (any, bool) {
	p.ExprCnt++
	if p.ExprCnt > p.maxExprCnt {
		panic(errMaxExprCnt)
	}

	var val any
	var ok bool
	switch expr := expr.(type) {
	case *actionExpr:
		val, ok = p.parseActionExpr(expr)
	case *andCodeExpr:
		val, ok = p.parseAndCodeExpr(expr)
	case *andExpr:
		val, ok = p.parseAndExpr(expr)
	case *anyMatcher:
		val, ok = p.parseAnyMatcher(expr)
	case *charClassMatcher:
		val, ok = p.parseCharClassMatcher(expr)
	case *choiceExpr:
		val, ok = p.parseChoiceExpr(expr)
	case *labeledExpr:
		val, ok = p.parseLabeledExpr(expr)
	case *litMatcher:
		val, ok = p.parseLitMatcher(expr)
	case *notCodeExpr:
		val, ok = p.parseNotCodeExpr(expr)
	case *notExpr:
		val, ok = p.parseNotExpr(expr)
	case *oneOrMoreExpr:
		val, ok = p.parseOneOrMoreExpr(expr)
	case *recoveryExpr:
		val, ok = p.parseRecoveryExpr(expr)
	case *ruleRefExpr:
		val, ok = p.parseRuleRefExpr(expr)
	case *seqExpr:
		val, ok = p.parseSeqExpr(expr)
	case *stateCodeExpr:
		val, ok = p.parseStateCodeExpr(expr)
	case *throwExpr:
		val, ok = p.parseThrowExpr(expr)
	case *zeroOrMoreExpr:
		val, ok = p.parseZeroOrMoreExpr(expr)
	case *zeroOrOneExpr:
		val, ok = p.parseZeroOrOneExpr(expr)
	default:
		panic(fmt.Sprintf("unknown expression type %T", expr))
	}
	return val, ok
}

func (p *parser) parseActionExpr(act *actionExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseActionExpr"))
	}

	start := p.pt
	val, ok := p.parseExprWrap(act.expr)
	if ok {
		p.cur.pos = start.position
		p.cur.text = p.sliceFrom(start)
		state := p.cloneState()
		actVal, err := act.run(p)
		if err != nil {
			p.addErrAt(err, start.position, []string{})
		}
		p.restoreState(state)

		val = actVal
	}
	if ok && p.debug {
		p.printIndent("MATCH", string(p.sliceFrom(start)))
	}
	return val, ok
}

func (p *parser) parseAndCodeExpr(and *andCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndCodeExpr"))
	}

	state := p.cloneState()

	ok, err := and.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, ok
}

func (p *parser) parseAndExpr(and *andExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAndExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	_, ok := p.parseExprWrap(and.expr)
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, ok
}

func (p *parser) parseAnyMatcher(any *anyMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseAnyMatcher"))
	}

	if p.pt.rn == utf8.RuneError && p.pt.w == 0 {
		// EOF - see utf8.DecodeRune
		p.failAt(false, p.pt.position, ".")
		return nil, false
	}
	start := p.pt
	p.read()
	p.failAt(true, start.position, ".")
	return p.sliceFrom(start), true
}

func (p *parser) parseCharClassMatcher(chr *charClassMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseCharClassMatcher"))
	}

	cur := p.pt.rn
	start := p.pt

	// can't match EOF
	if cur == utf8.RuneError && p.pt.w == 0 { // see utf8.DecodeRune
		p.failAt(false, start.position, chr.val)
		return nil, false
	}

	if chr.ignoreCase {
		cur = unicode.ToLower(cur)
	}

	// try to match in the list of available chars
	for _, rn := range chr.chars {
		if rn == cur {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of ranges
	for i := 0; i < len(chr.ranges); i += 2 {
		if cur >= chr.ranges[i] && cur <= chr.ranges[i+1] {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	// try to match in the list of Unicode classes
	for _, cl := range chr.classes {
		if unicode.Is(cl, cur) {
			if chr.inverted {
				p.failAt(false, start.position, chr.val)
				return nil, false
			}
			p.read()
			p.failAt(true, start.position, chr.val)
			return p.sliceFrom(start), true
		}
	}

	if chr.inverted {
		p.read()
		p.failAt(true, start.position, chr.val)
		return p.sliceFrom(start), true
	}
	p.failAt(false, start.position, chr.val)
	return nil, false
}

func (p *parser) incChoiceAltCnt(ch *choiceExpr, altI int) {
	choiceIdent := fmt.Sprintf("%s %d:%d", p.rstack[len(p.rstack)-1].name, ch.pos.line, ch.pos.col)
	m := p.ChoiceAltCnt[choiceIdent]
	if m == nil {
		m = make(map[string]int)
		p.ChoiceAltCnt[choiceIdent] = m
	}
	// We increment altI by 1, so the keys do not start at 0
	alt := strconv.Itoa(altI + 1)
	if altI == choiceNoMatch {
		alt = p.choiceNoMatch
	}
	m[alt]++
}

func (p *parser) parseChoiceExpr(ch *choiceExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseChoiceExpr"))
	}

	for altI, alt := range ch.alternatives {
		// dummy assignment to prevent compile error if optimized
		_ = altI

		state := p.cloneState()

		p.pushV()
		val, ok := p.parseExprWrap(alt)
		p.popV()
		if ok {
			p.incChoiceAltCnt(ch, altI)
			return val, ok
		}
		p.restoreState(state)
	}
	p.incChoiceAltCnt(ch, choiceNoMatch)
	return nil, false
}

func (p *parser) parseLabeledExpr(lab *labeledExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLabeledExpr"))
	}

	p.pushV()
	val, ok := p.parseExprWrap(lab.expr)
	p.popV()
	if ok && lab.label != "" {
		m := p.vstack[len(p.vstack)-1]
		m[lab.label] = val
	}
	return val, ok
}

func (p *parser) parseLitMatcher(lit *litMatcher) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseLitMatcher"))
	}

	start := p.pt
	for _, want := range lit.val {
		cur := p.pt.rn
		if lit.ignoreCase {
			cur = unicode.ToLower(cur)
		}
		if cur != want {
			p.failAt(false, start.position, lit.want)
			p.restore(start)
			return nil, false
		}
		p.read()
	}
	p.failAt(true, start.position, lit.want)
	return p.sliceFrom(start), true
}

func (p *parser) parseNotCodeExpr(not *notCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotCodeExpr"))
	}

	state := p.cloneState()

	ok, err := not.run(p)
	if err != nil {
		p.addErr(err)
	}
	p.restoreState(state)

	return nil, !ok
}

func (p *parser) parseNotExpr(not *notExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseNotExpr"))
	}

	pt := p.pt
	state := p.cloneState()
	p.pushV()
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	_, ok := p.parseExprWrap(not.expr)
	p.maxFailInvertExpected = !p.maxFailInvertExpected
	p.popV()
	p.restoreState(state)
	p.restore(pt)

	return nil, !ok
}

func (p *parser) parseOneOrMoreExpr(expr *oneOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseOneOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			if len(vals) == 0 {
				// did not match once, no match
				return nil, false
			}
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseRecoveryExpr(recover *recoveryExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRecoveryExpr (" + strings.Join(recover.failureLabel, ",") + ")"))
	}

	p.pushRecovery(recover.failureLabel, recover.recoverExpr)
	val, ok := p.parseExprWrap(recover.expr)
	p.popRecovery()

	return val, ok
}

func (p *parser) parseRuleRefExpr(ref *ruleRefExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseRuleRefExpr " + ref.name))
	}

	if ref.name == "" {
		panic(fmt.Sprintf("%s: invalid rule: missing name", ref.pos))
	}

	rule := p.rules[ref.name]
	if rule == nil {
		p.addErr(fmt.Errorf("undefined rule: %s", ref.name))
		return nil, false
	}
	return p.parseRuleWrap(rule)
}

func (p *parser) parseSeqExpr(seq *seqExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseSeqExpr"))
	}

	vals := make([]any, 0, len(seq.exprs))

	pt := p.pt
	state := p.cloneState()
	for _, expr := range seq.exprs {
		val, ok := p.parseExprWrap(expr)
		if !ok {
			p.restoreState(state)
			p.restore(pt)
			return nil, false
		}
		vals = append(vals, val)
	}
	return vals, true
}

func (p *parser) parseStateCodeExpr(state *stateCodeExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseStateCodeExpr"))
	}

	err := state.run(p)
	if err != nil {
		p.addErr(err)
	}
	return nil, true
}

func (p *parser) parseThrowExpr(expr *throwExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseThrowExpr"))
	}

	for i := len(p.recoveryStack) - 1; i >= 0; i-- {
		if recoverExpr, ok := p.recoveryStack[i][expr.label]; ok {
			if val, ok := p.parseExprWrap(recoverExpr); ok {
				return val, ok
			}
		}
	}

	return nil, false
}

func (p *parser) parseZeroOrMoreExpr(expr *zeroOrMoreExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrMoreExpr"))
	}

	var vals []any

	for {
		p.pushV()
		val, ok := p.parseExprWrap(expr.expr)
		p.popV()
		if !ok {
			return vals, true
		}
		vals = append(vals, val)
	}
}

func (p *parser) parseZeroOrOneExpr(expr *zeroOrOneExpr) (any, bool) {
	if p.debug {
		defer p.out(p.in("parseZeroOrOneExpr"))
	}

	p.pushV()
	val, _ := p.parseExprWrap(expr.expr)
	p.popV()
	// whether it matched or not, consider it a match
	return val, true
}
